### ISSUE TITLE
Versions are not set properly

### ISSUE THREAD

**Issue by mluppi** [cysec-platform/cysec-platform#28]
The switch-statement in the _Jenkinsfile_ refers to non-existent `main`-branch. In this repository, it should be the `master`-branch. Additionally, the versions across POMs do not match.

https://github.com/cysec-platform/cysec-platform/blob/699273df19af1f15f085d9bcf2cbfb7ba38230eb/Jenkinsfile#L18-L28

**Currently, the versions are as follows:**
`coach_platform` (root) -> `0.2.0`
`cysec_backend` -> `0.2.0`
`cysec_bridge` -> `0.2.1-SNAPSHOT`

**Comment by martingwerder** [comment]
Not sure if I share this opinion. The main/master dicussion was lauched by many companies (see [here](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/). Unfortunately this is more a political than a technical topic. As "main" was already the term on gitlab I would vote for the term "main". 

Second the mismatching versions: There my opinion is a bit more differentiating. In the current state they all started off with the same versions. I can see already that they will evolve at different sppeds (e.g., CySeC-bridge will only have a new version when interfacing to coaches is adopted. Instead of pushing new empty versions I would like to keep the current versioning. The question is, however, how do we keep track of which versions go together in such a case? (tags?). Opinions and arguments in favor or against it are highly welcomed.

**Comment by mluppi** [comment]
> Not sure if I share this opinion. Many companies launched the main/master discussion (see [here](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/)). Unfortunately, this is more a political than a technical topic. As "main" was already the term on GitLab, I would vote for the term "main".

I absolutely agree with you (@martingwerder) regarding the political aspect of this discussion. I do not see a reason for renaming the branch to `main` instead of changing the switch-statement. Right now, this is an issue no matter how we decide to move on from here: **A)** renaming `master` to `main` or **B)** correcting the switch statement. Therefore, I wrote "_In this repository [...]_"... In fact, the default branch is **not** `main` right now.

> Second, the mismatching versions. There, my opinion is a bit more differentiating. In the current state, they all started with identical versions. I can see already that they will evolve at different speeds (e.g., CySeC-bridge will only have a new version when interfacing with coaches is adopted. Instead of pushing new empty versions, I would like to keep the current versioning. However, the question is: How do we keep track of which versions go together in such a case? (tags?). Opinions and arguments in favour or against it are highly welcomed.

I agree that the versions do not necessarily need to be the same for the different modules. However, properly managing different versions in the same repository is not trivial. Maybe we could move the bridge into its own repository which would make things easier. Currently only one dependency is managed plus some test dependencies. The effort of developing a **stable** _automated_ build and release involving different versions is likely not worth the benefit of having a single repository with a parent-POM. The compatibility between backend and bridge is governed by the defined version in the backend POM. It's more difficult to manage this for the libraries contained in the coaches. Backwards-compatibility is absolutely crucial here.

**Comment by martingwerder** [comment]
Not sure if I agee with the second.

I would propose the following:

1. Lets rename the "master" branch (in all cysec repos) ro "main"
2. Create a new issue creating a bridge (using a filtering POM) containing a subset of interfaces and files from the platform (that would guarantee consistency with the platform)
3. Keep the versioning inconsistent and close this issue.

Other opinions?

**Comment by mluppi** [comment]
1. I renamed all `master` branches to `main` in all repositories of this project where I have access.
    Local clones can be updated by running:
    ```
    git branch -m master main
    git fetch origin
    git branch -u origin/main main
    git remote set-head origin -a
    ```

2. If by "filtering POM" you mean running the Maven Assembly Plugin to include/exclude parts of the backend-module, I would advise against it. I see two robust ways to manage the versioning: **A)** the bridge has its own repository (independent versioning) and is used as a dependency by the backend and the coaches or **B)** the bridge is always in sync with the backend version which is much simpler to handle. We can provide a compatibility table which shows what (lower) versions of the bridge are (still) supported by the platform. As long as we ensure backwards-compatibility, there is no problem providing a higher version of the bridge at runtime (by the backend) than the one being used at compile-time (by the coaches). Probably it would be good to already implement [version checking](http://apr.apache.org/versioning.html#vsncheck) early on so we can enforce versions should the need arise in the future. My opinion is to use variant B.


3. In commit 7c4004b64270f6001095f55dee9b0706dd5a267a, the `cysec_bridge` was raised to the next snapshot version but not `cysec_backend`.

**Comment by mluppi** [comment]
As discussed in the meeting today, we will use the same versions from now on forward. As the project uses the [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) there will be a `release` branch for each release where the appropriate versions will be set before merging to `main`. In consequence, `main` always holds the latest released version. The `develop` branch contains SNAPSHOT versions for the next release.

**Comment by mluppi** [comment]
The versions are now set according to the last comment. The `development` branch has been renamed to `develop` across all CYSEC repositories to be in-sync with Gitflow.

The following commands can be executed locally to reflect the name change:
```
git branch -m development develop
git fetch origin
git branch -u origin/develop develop
```
