### ISSUE TITLE
Error for empty text-question

### ISSUE THREAD

**Issue by mluppi** [cysec-platform/cysec-platform#30]
When an empty value for a previously filled out text-question is sent to the backend, the following error is displayed in the UI (example):

```
Error: Couldn't update answer on:
http://localhost:8080/cysec/api/rest/coaches/lib-company.default/answers/company-q130: 400
```

_Trigger:_ `onchange`-event on the `textarea` handled by JavaScript

**Comment by simonfreiermuth** [comment]
This issue seems to be fixed, as the error cannot be reproduced.
