### ISSUE TITLE
Link to profile in header is wrong

### ISSUE THREAD

**Issue by mluppi** [cysec-platform/cysec-platform#8]
The link to the profile in the header-menu statically links to a wrong reference.

A configurable value `cysec_header_profile` should be used instead and only be displayed when the authentication strategy is not _Basic_.

**Comment by martingwerder** [comment]
The header profile is there. Now I need to write a sensible processing for the config value.

Proposed something like https://{host}:{port}/{context}/app/users.jsp

Closing issue  #6

**Comment by mluppi** [comment]
> The header profile is there. Now I need to write a sensible processing for the config value.
> 
> Proposed something like https://{host}:{port}/{context}/app/users.jsp

@martingwerder As far as I understood, these two links are referring to external auth (e.g. Keycloak) to show the user's profile or trigger logout. A link to `users.jsp` already exists here:
https://github.com/cysec-platform/cysec-platform/blob/699273df19af1f15f085d9bcf2cbfb7ba38230eb/cysec_backend/src/main/webapp/WEB-INF/templates/header/cysec.jsp#L15
