### ISSUE TITLE
The CSS-File of the last page is broken

### ISSUE THREAD

**Issue by martingwerder** [cysec-platform/cysec-platform#91]
The CSS-File of the last page is broken. This leads to a suboptimal page rendering.

**Comment by simonfreiermuth** [comment]
Insofar as this relates to the "broken" summary page, this issue is not related to the plattform but to the coaches. Prolem was a wrong link in `summary.jsp`. The [cysec-coach-template PR](https://gitlab.fhnw.ch/itmeetsot/cysec-coach-template/-/merge_requests/1) contains a fix.
